### ISSUE TITLE
Datagrid with filter with many columns - not apply filter

### ISSUE THREAD

**Issue by vaclav-domin** [tom-englert/DataGridExtensions#34] opened 2020-06-27 08:50 UTC
When datagrid has more columns then window width - filter active for column on visible area.
When scroll to right columns, filter deactivated and datagrid show all columns.
When scoll back, filter is back.

**Comment by tom-englert** [comment] 2020-06-27 14:31
Thats probably a duplicate of #23 - do you have column virtualization enabled?

**Closed** 2020-06-28 14:53 UTC
Labels: duplicate
